# Generated by Django 3.1.3 on 2020-12-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesApp', '0002_auto_20201224_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
